version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: event-monitoring-postgres
    environment:
      POSTGRES_DB: event_monitoring_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - event-monitoring-network


volumes:
  postgres_data:

networks:
  event-monitoring-network:
    driver: bridge