services:
  event-monitoring-service:
    container_name: event-monitoring-service
    build:
      context: .
      args:
        GH_TOKEN: ${GH_TOKEN}
    ports:
      - '3002:3002'
    environment:
      - NODE_ENV=development
    depends_on:
      - redis
      - nats

  redis:
    image: redis:7-alpine
    container_name: event-monitoring-redis
    command: redis-server --requirepass redis-password
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  nats:
    image: nats:2.10-alpine
    container_name: event-monitoring-nats
    ports:
      - '4222:4222'
      - '8222:8222'
    command: ['nats-server', '--jetstream', '--http_port', '8222']

volumes:
  postgres_data:
  redis_data:
